### ISSUE TITLE
Typo in name of cache?

### ISSUE THREAD

**Issue by proinsias** [mxab/pre-commit-trivy#2]
This is a quick one. Should `.pre-commit-trivv-cache` by `.pre-commit-trivy-cache`?

**Comment by mxab** [comment]
Oh yeah thanks. Will fix it on the weekend.
I'll also try to get precommit to use a named volume so the cache should be faster

**Comment by mxab** [comment]
fixed in 3dfc9a9f8133ae538dfbbe3379dab18545d943f0

**Comment by mxab** [comment]
unfortunately named volumes is a bit tricky with pre-commit as it automatically sets uid/gid of the host user and named volumes are root
